# Generated by Django 4.2 on 2023-08-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogtracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
