# Generated by Django 4.2 on 2023-09-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogtracks', '0003_alter_animal_owner_alter_visit_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
