# Generated by Django 4.2 on 2023-09-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogtracks', '0004_animal_breed_animal_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
