# Generated by Django 4.2 on 2023-09-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogtracks', '0006_alter_animal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Pet name'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
