# Generated by Django 4.2 on 2023-09-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogtracks', '0007_alter_animal_name_alter_animal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
