# Generated by Django 4.2 on 2023-10-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogtracks', '0009_alter_animal_photo_alter_animal_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('request', 'Request'), ('confirm', 'Confirm'), ('complete', 'Complete'), ('cancel', 'Cancel')], default='request', max_length=10),
        ),
    ]
