# Generated by Django 4.2 on 2023-10-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogtracks', '0010_alter_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
