# Generated by Django 4.2 on 2023-10-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogtracks', '0011_visit_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('request', 'Requested'), ('confirm', 'Confirmed'), ('complete', 'Completed'), ('cancel', 'Cancelled')], default='request', max_length=10),
        ),
    ]
